apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
  labels:
    app: MYAPP
spec:
  replicas: 3
  selector:
    matchLabels:
      app: MYAPP
  template:
    metadata:
      labels:
        app: MYAPP
    spec:
      containers:
        - name: my-first-deployment
          image: stacksimplify/kubenginx:2.0.0
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - name: web
              containerPort:  80
              protocol: TCP
          
---

apiVersion: v1
kind: Service
metadata:
  name: my-first-service
  labels:
    app: MYAPP
spec:
  selector:
    app: MYAPP
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80