apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: tcs-test.mysql.database.azure.com
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  usermgmt
  labels:
    app:  usermgmt
spec:
  selector:
    matchLabels:
      app: usermgmt
  replicas: 1
  template:
    metadata:
      labels:
        app:  usermgmt
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']  
      containers:
        - name:  usermgmt
          image: stacksimplify/kube-usermgmt-webapp:1.0.0-MySQLDB
          imagePullPolicy: Always
          resources:
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "webappdb"            
            - name: DB_USERNAME
              value: "loki@tcs-test"            
            - name: DB_PASSWORD
              value: "StackUP$890" 
          ports:
            - containerPort:  8080
              name:  usermgmt

---

apiVersion: v1
kind: Service
metadata:
  name: usermgmt
  labels:
    app:  usermgmt
spec:
  selector:
    app: usermgmt
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
