apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name:  managed-premium-retain-sc
provisioner: disk.csi.azure.com
parameters:
  storageaccounttype: Premium_LRS 
  kind: managed
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
spec:
  storageClassName: managed-premium-retain-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
