apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name:  azure-file-sc
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-pvc
spec:
  storageClassName: azure-file-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
